AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ywiki
Resources:
  ywikiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.acmerocket.ywiki.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/ywiki-0.8-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ywikiApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: ywikiApi
